from .ActivityController import *
from .CategoryController import *
from .TemplateController import *
from .WorkController import *
from .CommentController import *
from .ClassController import *
from .TeacherController import *
from .TeamController import *
from .StudentController import *
from .TokensController import *