# Generated by Django 4.2.1 on 2023-05-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=5000)),
                ('link', models.URLField(default='', null=True)),
            ],
            options={
                'db_table': 'Activities',
            },
        ),
    ]
