# Generated by Django 4.2.6 on 2023-10-19 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
