# Generated by Django 4.2.1 on 2023-05-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(default='INCOMPLETE', max_length=100),
        ),
        migrations.AlterModelTable(
            name='activity',
            table=None,
        ),
    ]
