# Generated by Django 4.2.1 on 2023-10-11 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0002_activity_status_alter_activity_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='link',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='name',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='status',
        ),
        migrations.AddField(
            model_name='activity',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='submission_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='activity',
            name='work_submission',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
