# Generated by Django 4.2.6 on 2023-10-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0003_remove_activity_link_remove_activity_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
