# Generated by Django 4.2.6 on 2023-10-19 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0004_alter_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_class',
        ),
        migrations.RemoveField(
            model_name='template',
            name='category',
        ),
    ]
