# Generated by Django 4.2.6 on 2023-10-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0005_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
