# Generated by Django 4.2.6 on 2023-10-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0010_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('year_level', models.PositiveIntegerField()),
                ('section', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
