# Generated by Django 4.2.6 on 2023-10-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
