# Generated by Django 4.2.6 on 2023-11-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0010_activity_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='total_score',
            field=models.IntegerField(default=100),
        ),
    ]
