# Generated by Django 4.2.6 on 2023-10-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0011_work_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='file_attachment',
            field=models.FileField(blank=True, upload_to='work_submissions/'),
        ),
    ]
