# Generated by Django 4.2.6 on 2023-10-17 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0011_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
