# Generated by Django 4.2.6 on 2023-10-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0012_work_file_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
