# Generated by Django 4.2.6 on 2023-10-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0013_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
