# Generated by Django 4.2.6 on 2023-10-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0013_comment_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='name',
            new_name='title',
        ),
    ]
