# Generated by Django 4.2.7 on 2023-11-06 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0014_template_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amt.course'),
        ),
    ]
