# Generated by Django 4.2.6 on 2023-10-17 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0015_team_class_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='class_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amt.class'),
        ),
    ]
