# Generated by Django 4.2.6 on 2023-10-17 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0014_rename_name_template_title'),
        ('amt', '0017_student'),
    ]

    operations = [
    ]
