# Generated by Django 4.2.6 on 2023-10-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('amt', '0025_alter_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user_permissions',
            field=models.ManyToManyField(null=True, related_name='teachers_permissions', to='auth.permission'),
        ),
    ]
