from .ActivitySerializer import *
from .CategorySerializer import *
from .TemplateSerializer import *
from .WorkSerializer import *
from .CommentSerializer import *
from .ClassSerializer import *
from .TeamSerializer import *
from .StudentSerializer import *
from .UserSerializer import *
from .AuthTokenSerializer import *