from .ActivitySerializer import *
from .CategorySerializer import *
from .TemplateSerializer import *
from .WorkSerializer import *
from .CommentSerializer import *
from .ClassSerializer import *
from .TeacherSerializer import *
from .TeamSerializer import *
from .StudentSerializer import *